app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", views.Landing, name="Landing"),

    path("camp_reg/", views.CampReg, name="CampReg"),
    path("police_reg/",views.PoliceReg, name="PoliceReg"),
    path("public_reg/",views.PublicReg,name="PublicReg"),
    path("volunteer_reg/", views.VolunteerReg, name="VolunteerReg"),
   # path("view_admin/",views.ViewAdmin,name="ViewAdmin"),

    path("camp_tables/",views.CampTable, name="CampTable"),
    path("station_tables/",views.StationTable, name="StationTable"),
    path("public_tables/",views.PublicTable, name="PublicTable"),
    path("volunteer_tables/",views.VolunteerTable, name="VolunteerTable"),
    path("camp_needs_table/",views.CampNeedsTable, name="CampNeedsTable"),

    path("login/",views.UserLogin,name="UserLogin"),
    path("logout/",views.Logout,name="Logout"),

    path("campHome/",views.CampHome, name='CampHome'),
    path("stationHome/",views.StationHome, name='StationHome'),
    path("publicHome/",views.PublicHome, name='PublicHome'),
    path("volunteerHome/",views.VolunteerHome, name='VolunteerHome'),

    path("editcamp/",views.EditCamp, name='EditCamp'),                             
    path("editstation/",views.EditStation, name='EditStation'),
    path("editpublic/",views.EditPublic, name='EditPublic'),
    path("editvolunteer/",views.EditVolunteer, name='EditVolunteer'),

    path('admin_view/',views.ViewAdmin2,name='ViewAdmin2'),

    path('camp_user_reg',views.CampAddUser,name="CampAddUser"),                     #         path of adding camp user
    path('campusersview',views.CampUsersView,name="CampUsersView"),                 #         path of viewing camp user
    path('camp_user_edit/<int:id>',views.EditCampUser,name="EditCampUser"),         #         path of editing camp user
    path('camp_user_delete/<int:id>/',views.CampUserDelete,name="CampUserDelete"),  #         path of deleting camp user

    path('camp_search',views.CampSearch,name="CampSearch"),

    path('camp_needs',views.CampNeedsSubmit,name="CampNeedsSubmit"),
    path('needs_view',views.NeedsViewTable,name="NeedsViewTable"),
    path('edit_camp_need/<int:id>',views.EditCampNeed,name="EditCampNeed"),
    path('delete_camp_need/<int:id>/',views.CampNeedsDelete,name="DeleteCampNeed"),
    path('set_camp_need_status/<int:id>',views.SetCampNeedStatus,name="SetCampNeedStatus"),

    path('camp_person_search',views.SearchCampPerson,name="SearchCampPerson"),
    path('person_search',views.SearchPerson,name="SearchPerson"),
    path('ReportMissingPerson/<int:id>',views.ReportMissingPerson,name="ReportMissingPerson"),    # missing person search


    path('camp_alert',views.CampAlerts,name="CampAlerts"),
    path('camp_alert_table',views.CampAlertTable,name="CampAlertTable"),
    path('alert_table',views.AlertCampTable,name="AlertCampTable"), 
    path('delete_alert/<int:id>',views.DeleteAlert,name="DeleteAlert"), 
    
    #       Request for volunteers required by camp

    path('volunteer_req',views.VolunteerReq,name="VolunteerReq"),
    path('volunteer_req_table',views.VolunteerReqTable,name="VolunteerReqTable"),
    path('req_volunteer_table',views.ReqVolunteerTable,name="ReqVolunteerTable"),
    path('edit_volunteer_req/<int:id>',views.EditVolunteerReq,name="EditVolunteerReq"),
    path('delete_volunteer_req/<int:id>',views.DeleteVolunteerReq,name="DeleteVolunteerReq"),

    path('volunteer_allocate_table/<int:id>/<int:requestid>',views.VolunteerAllocateTable,name="VolunteerAllocateTable"),
    path('VolAllocateNow/<int:campid>/<int:id>/<int:volreqid>',views.VolAllocateNow,name="VolAllocateNow"),
    path('VolDeAllocate/<int:campid>/<int:id>/<int:volreqid>',views.VolDeAllocate,name="VolDeAllocate"),
    
    path('Notification',views.Notification,name="Notification"),

    path('PublicComplaint',views.PublicComplaint,name="PublicComplaint"),
    path('ViewComplaints',views.ViewComplaints,name="ViewComplaints"),
    path('ListComplaints',views.ListComplaints,name="ListComplaints"),
    path('EditComplaint/<int:id>',views.EditComplaint,name="EditComplaint"),
    path('DeleteComplaint/<int:id>',views.DeleteComplaint,name="DeleteComplaint"),
    path('allocated_vol_List',views.AllocatedVolList,name="AllocatedVolList"),
    path('ComplaintReply/<int:id>',views.ComplaintReply,name="ComplaintReply"),
    path('ShowReply/<int:id>',views.ShowReply,name="ShowReply"),
    path('allocated_vol_List',views.AllocatedVolList,name="AllocatedVolList"),            #    List of the volunteers assingned to the camp
    path('ScheduleDuty/<int:camp>/<int:volunteer>',views.ScheduleDuty,name="ScheduleDuty"),
    path('ReScheduleDuty/<int:camp>/<int:volunteer>',views.ReScheduleDuty,name="ReScheduleDuty"),

    path('FundAllocationRequest',views.FundAllocationRequest,name="FundAllocationRequest"),
    path('FundAllocationRequestList',views.FundAllocationRequestList,name="FundAllocationRequestList"),
    path('FundAllocationRequestEdit/<int:id>',views.FundAllocationRequestEdit,name="FundAllocationRequestEdit"),
    path('FundAllocationRequestDelete/<int:id>',views.FundAllocationRequestDelete,name="FundAllocationRequestDelete"),
    path('FundAllocationRequestView',views.FundAllocationRequestView,name="FundAllocationRequestView"),
    path('ViewFundAllocationRequest/<int:id>',views.ViewFundAllocationRequest,name="ViewFundAllocationRequest"),
    path('AllocateFund/<int:id>',views.AllocateFund,name="AllocateFund"),
    path('Payment/<int:id>/<int:amount>',views.Payment,name="Payment"),
    # path('ScheduleNotify/<int:camp>',views.ScheduleNotify,name="ScheduleNotify"),
    path('ViewMissingReports',views.ViewMissingReports,name="ViewMissingReports"),
    path('AddMissingStatus/<int:id>',views.AddMissingStatus,name="AddMissingStatus"),
    path('ViewMissingList',views.ViewMissingList,name="ViewMissingList"),
    path('EditMissingStatus/<int:id>',views.EditMissingStatus,name="EditMissingStatus"),
    path('DeleteMissingStatus/<int:id>',views.DeleteMissingStatus,name="DeleteMissingStatus"),
     

    path('StationSearch',views.StationSearch,name="StationSearch"),


    path('EmergencyMessageAlert',views.EmergencyMessageAlert,name="EmergencyMessageAlert"),
    path('EmergencyAlertList',views.EmergencyAlertList,name="EmergencyAlertList"),
    path('EditEmergencyAlert/<int:id>',views.EditEmergencyAlert,name="EditEmergencyAlert"),
    path('DeleteEmergencyAlert/<int:id>',views.DeleteEmergencyAlert,name="DeleteEmergencyAlert"),
    path('EmergencyAlertView',views.EmergencyAlertView,name="EmergencyAlertView"),

    path('TableCamp',views.TableCamp,name="TableCamp"),
    path('CampEnquiry/<int:id>',views.CampEnquiry,name="CampEnquiry"),
    path('EnquiryTable',views.EnquiryTable,name="EnquiryTable"),
    path('EnquiryReply/<int:id>',views.EnquiryReply,name="EnquiryReply"),
    path('EnqResponseTable',views.EnqResponseTable,name="EnqResponseTable"),

    path('VehicleMissing/<int:id>',views.VehicleMissing,name="VehicleMissing"),
    path('VehicleMissingReports',views.VehicleMissingReports,name="VehicleMissingReports"),
    path('VehicleStatus/<int:id>',views.VehicleStatus,name="VehicleStatus"),
    path('EditVehicleStatus/<int:id>',views.EditVehicleStatus,name="EditVehicleStatus"),
    path('DeleteVehicleStatus/<int:id>',views.DeleteVehicleStatus,name="DeleteVehicleStatus"),
    path('VehicleList',views.VehicleList,name="VehicleList"),
    path('ComfirmPassCamp',views.ComfirmPassCamp,name="ComfirmPassCamp"),

    path('AddProduct',views.AddProduct,name="AddProduct"),
    path('ViewProduct',views.ViewProduct,name="ViewProduct"),
    path('EditProduct/<int:id>',views.EditProduct,name="EditProduct"),
    path('DeleteProduct/<int:id>',views.DeleteProduct,name="DeleteProduct"),
    path('ProdUsage/<int:id>',views.ProdUsage,name="ProdUsage"),
    path('MonthlyReport',views.MonthlyReport,name="MonthlyReport"),
    path('PerDayReport',views.PerDayReport,name="PerDayReport"),

    path('send_otp_view',views.send_otp_view,name="send_otp_view"),
    path('verify_otp_view/<str:email>/',views.verify_otp_view,name="verify_otp_view"),
    path('reset_password_view',views.reset_password_view,name="reset_password_view"),
    

    path("weather/", views.get_weather, name="weather"),
    path('misschecking/', views.misschecking, name='misschecking'),
    
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) # new 

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
]

app/forms.py
from django import forms
from .models import *
# from .models import Camp, Login, Police, Public, Volunteer, CampUser,CampNeeds,CampAlert,VolunteerRequest,Complaint,Duty,FundAllocationModel,FundPayment,EmergencyAlert

class CampForm(forms.ModelForm):
    
    class Meta:
        model=Camp
        fields=['camp_name','full_address','district','city','panchayath','thaluk','contact']

class LoginForm(forms.ModelForm):
    class Meta:
        model=Login
        fields=['email','password']

class PoliceForm(forms.ModelForm):
    class Meta:
        model=Police
        fields=['station_id','address_line_1','address_line_2','district','city','contact']

class PublicForm(forms.ModelForm):
    class Meta:
        model=Public
        fields=['fullname','address','pincode','district','city','panchayath','village','contact']

class VolunteerForm(forms.ModelForm):
    class Meta:
        model=Volunteer
        fields=['volunteer_name','gender','date_of_birth','aadhar_no','contact']
        widgets={
            'date_of_birth' : forms.DateInput(attrs={'class':'form-control','type':'date'})
        }

class LoginCheck(forms.Form):
    email=forms.CharField(max_length=100)
    password=forms.CharField(widget=forms.PasswordInput)

class LoginEditForm(forms.ModelForm): # form for profile editing
    class Meta:
        model=Login
        fields=['email']


class CampUserForm(forms.ModelForm):
    class Meta:
        model=CampUser
        fields=['photo','full_name','address','district','city','contact_no','aadhar_no','panchayath','village','thaluk']
        widgets = {
            'full_name': forms.TextInput(attrs={
                'class': 'custom-input peer',
                'placeholder': '',
                'required': True,
                'pattern': '^[A-Za-z ]{2,50}$',
                'title': 'Name must be letters and spaces only (2–50 characters)'
            }),
            'address': forms.TextInput(attrs={
                'class': 'custom-input',
                'placeholder': 'Address',
                'required': True,
                'pattern': '^[A-Za-z ]{2,50}$',
                'title': 'Name must be letters and spaces only (2–50 characters)'
            }),
         }

class CampNeedsForm(forms.ModelForm):
    class Meta:
        model=CampNeeds
        fields=['needs'] 

class CampAlertForm(forms.ModelForm):
    class Meta:
        model=CampAlert
        fields=['emergency_message']

class VolunteerReqForm(forms.ModelForm):
    class Meta:
        model=VolunteerRequest
        fields=['no_of_volunteers','volunteer_details']

class ComplaintForm(forms.ModelForm):
    class Meta:
        model=Complaint
        fields=['complaint_sub','complaint']

class ComplaintReplyForm(forms.ModelForm):
    class Meta:
        model=Complaint
        fields=['reply']

CHOICES = [
    ('Cooking', 'Cooking'),
    ('Cleaning', 'Cleaning'),
    ('Cloth collecting', 'Cloth collecting'),
    ('Survey', 'Survey')
]

class DutyForm(forms.ModelForm):
    spec = forms.ChoiceField(choices=CHOICES)

    class Meta:
        model = Duty
        fields = ['spec', 'duty']

class FundAllocationForm(forms.ModelForm):
    class Meta:
        model=FundAllocationModel
        fields=['image','full_name','full_address','district','city','panchayath','ration_card_no','contact','other_details']


class MissingPersonForm(forms.ModelForm):
    class Meta: 
        model=MissingPerson
        fields=['photo','name','address','gender','age','other_details']

class MissingPersonStatusForm(forms.ModelForm):
    class Meta:
        model=MissingPerson
        fields=['status']

class FundPaymentForm(forms.ModelForm):
    class Meta:
        model=FundPayment
        fields=['name_on_card','card_no','expiring_date','cvv_no']
        widgets={
            'expiring_date' : forms.DateInput(attrs={'class':'form-control','type':'date'})
        }
        
class EmergencyAlertForm(forms.ModelForm):
    class Meta:
        model=EmergencyAlert
        fields=['alert_message']

class EnquiryForm(forms.ModelForm):
    class Meta:
        model=Enquiry
        fields=['enq']

class EnquiryResponseForm(forms.ModelForm):
    class Meta:
        model=Enquiry
        fields=['response']

class VehicleForm(forms.ModelForm):
    class Meta:
        model=Vehicle
        fields=['category','company','model_name','vehicle_num','missing_place','missing_date']
        widgets={
            'missing_date':forms.DateInput(attrs={'class':'form-control','type':'date'})
        }
    
class VehicleStatusForm(forms.ModelForm):
    class Meta:
        model=Vehicle
        fields=['status']


class ChangePasswordForm(forms.Form):                   #      form for changing passwo
    current_pass=forms.CharField(max_length=30)
    new_pass=forms.CharField(widget=forms.PasswordInput)
    confirm_pass=forms.CharField(widget=forms.PasswordInput)


products=[
    ('','--select an option--'),
    ('Cloths' , 'Cloths'),
    ('Food items' , 'Food items'),
    ('Medicines' , 'Medicines'),
]

class ProductForm(forms.ModelForm):

    prod_category = forms.ChoiceField(
        choices=products
        # widget=forms.Select(attrs={'placeholder': 'Select a category'})
    )

    class Meta:
        model = Product
        fields = ['prod_category', 'prod_name', 'quantity', 'prod_description']
        widgets = {
            'prod_name': forms.TextInput(attrs={'placeholder': 'Enter product name'}),
            'quantity': forms.NumberInput(attrs={'placeholder': 'Enter quantity'}),
            'prod_description': forms.Textarea(attrs={'placeholder': 'Enter product description'}),
        }

class ProductUsageForm(forms.ModelForm):
    class Meta:
        model=ProductUsage
        fields=['prod_quantity']


class ReportSearchForm(forms.Form):
    date = forms.DateInput(attrs={'class':'form-control','type':'date'})

#  forgot password section

class EmailForm(forms.Form):  
    email = forms.EmailField()


class OTPForm(forms.Form):
    email = forms.EmailField()
    otp = forms.CharField(max_length=6)


class ResetPasswordForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data.get('new_password') != cleaned_data.get('confirm_password'):
            raise forms.ValidationError("Passwords do not match.")


class misscheck(forms.Form):
    pic=forms.ImageField()

app/templates/common/campreg.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Login Page</title>
  <link href="{% static 'output.css' %}" rel="stylesheet">
</head>
<body class="bg-white text-gray-800">

  <!-- Navbar -->
  <nav class="flex items-center justify-between px-6 md:px-16 py-4 bg-white shadow">
    <div class="flex items-center gap-2">
      <img src="{% static 'logo.png' %}" class="w-[50px] h-[50px]" alt="Logo">
      <span class="text-2xl font-bold text-blue-800">Disaster Management System</span>
    </div>
    <div>
      <a href="/" class="text-blue-600 hover:underline"><button
        id="navRegisterBtn"
        class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition"
      >
        Back
      </button></a>
    </div>
  </nav>

  <!-- Hero Section -->
  <section class="flex flex-col md:flex-row items-center justify-center min-h-[80vh] px-6 py-12 bg-gray-50">
    
    <!-- Left Image -->
    <div class="w-full md:w-1/2 flex justify-center mb-10 md:mb-0">
      <img src="{% static 'register.jpg' %}" alt="Login Visual" class="w-2/3 md:w-3/4">
    </div>

    <!-- Right Login Form -->
    <div class="w-full md:w-1/3 bg-white p-8 rounded-lg shadow-md">
      <h2 class="text-2xl text-center font-semibold text-blue-700 mb-6">Register</h2>
  <form method="post">
    {% csrf_token %}
    <div class="relative z-0 w-full mb-5 group">
      <input
        type="text"
        id="id_camp_name"
        class="custom-input peer"
        name="camp_name"
        maxlength="100"
        placeholder=""
        required
      />
      <label for="id_camp_name" class="custom-label">Camp Name:</label>
    </div>
    
    <div class="relative z-0 w-full mb-5 group">
      <input
        type="text"
        id="id_full_address"
        class="custom-input peer"
        name="full_address"
        maxlength="255"
        placeholder=""
        required
      />
      <label for="id_full_address" class="custom-label">Full Address:</label>
    </div>
    
    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-5 group">
        <input
          type="text"
          id="id_district"
          class="custom-input peer"
          name="district"
          maxlength="100"
          placeholder=""
          required
        />
        <label for="id_district" class="custom-label">District:</label>
      </div>
    
      <div class="relative z-0 w-full mb-5 group">
        <input
          type="text"
          id="id_city"
          class="custom-input peer"
          name="city"
          maxlength="100"
          placeholder=""
          required
        />
        <label for="id_city" class="custom-label">City:</label>
      </div>
    </div>
    
    <div class="grid md:grid-cols-2 md:gap-6">
      <div class="relative z-0 w-full mb-5 group">
        <input
          type="text"
          id="id_panchayath"
          class="custom-input peer"
          name="panchayath"
          maxlength="100"
          placeholder=""
          required
        />
        <label for="id_panchayath" class="custom-label">Panchayath:</label>
      </div>
    
      <div class="relative z-0 w-full mb-5 group">
        <input
          type="text"
          id="id_thaluk"
          class="custom-input peer"
          name="thaluk"
          maxlength="100"
          placeholder=""
          required
        />
        <label for="id_thaluk" class="custom-label">Thaluk:</label>
      </div>
    </div>
    
    <div class="relative z-0 w-full mb-5 group">
      <input
        type="text"
        id="id_contact"
        class="custom-input peer"
        name="contact"
        maxlength="15"
        placeholder=""
        required
      />
      <label for="id_contact" class="custom-label">Contact:</label>
    </div>
    <div class="relative z-0 w-full mb-5 group">
      <input
        type="email"
        id="id_email"
        class="custom-input peer"
        name="email"
        maxlength="100"
        placeholder=""
        required
      />
      <label for="id_email" class="custom-label">Email:</label>
    </div>
    
    <div class="relative z-0 w-full mb-5 group">
      <input
        type="password"
        id="id_password"
        class="custom-input peer"
        name="password"
        maxlength="100"
        placeholder=""
        required
      />
      <label for="id_password" class="custom-label">Password:</label>
    </div>
    <div>
      {% if messages %}
        {% for message in messages %}
          <div class="text-red-500 text-sm mb-2">
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
    </div>
    
    <button type="submit" class="w-full bg-blue-600 text-white py-2 rounded-md hover:bg-blue-700 transition">
      Register
    </button>
  </form>
  </section>

  <!-- Footer -->
  <footer class="text-center py-6 border-t border-gray-200 bg-white text-gray-600">
    &copy; 2025 MyCompany. All rights reserved.
  </footer>

  <script>
    document.addEventListener('DOMContentLoaded', function () {
      function handleValidation(input, options) {
        const feedback = document.createElement('small');
        feedback.style.display = 'block';
        feedback.style.marginTop = '4px';
        input.parentNode.appendChild(feedback);
  
        function validate() {
          const value = input.value.trim();
  
          if (!value) {
            feedback.textContent = '❌ This field is required';
            feedback.style.color = 'red';
            return false;
          }
  
          if (options.pattern && !options.pattern.test(value)) {
            feedback.textContent = '❌ ' + options.invalidMsg;
            feedback.style.color = 'red';
            return false;
          }
  
          feedback.textContent = '✅ ' + options.validMsg;
          feedback.style.color = 'green';
          return true;
        }
  
        input.addEventListener('input', validate);
        return validate;
      }
  
      const fields = [
        { name: 'camp_name' },
        { name: 'full_address' },
        { name: 'district' },
        { name: 'city' },
        { name: 'panchayath' },
        { name: 'thaluk' },
        {
          name: 'contact',
          pattern: /^[0-9]{7,15}$/,
          validMsg: 'Valid contact number',
          invalidMsg: 'Enter a valid number (7–15 digits)'
        },
        {
          name: 'email',
          pattern: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
          validMsg: 'Valid email address',
          invalidMsg: 'Enter a valid email address'
        },
        {
          name: 'password',
          pattern: /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/,
          validMsg: 'Strong password',
          invalidMsg: 'Min 8 chars, 1 uppercase, 1 lowercase, 1 number, 1 special char'
        }
      ];
  
      const validators = [];
  
      fields.forEach(field => {
        const input = document.querySelector(`input[name="${field.name}"]`);
        if (input) {
          validators.push(
            handleValidation(input, {
              pattern: field.pattern,
              validMsg: field.validMsg || 'Looks good!',
              invalidMsg: field.invalidMsg || 'Invalid input'
            })
          );
        }
      });
  
      const form = document.querySelector('form');
      form.addEventListener('submit', function (e) {
        let allValid = true;
        validators.forEach(validate => {
          if (!validate()) allValid = false;
        });
  
        if (!allValid) {
          e.preventDefault();
          alert("❌ Please correct the highlighted errors.");
        }
      });
    });
  </script>
  
  
  
</body>
</html>

app/templates/common/reset_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
    <link href="{% static 'output.css' %}" rel="stylesheet" />
  </head>
  <body class="bg-white min-h-[100vh] text-gray-800">
    <!-- Navbar -->
    <nav
      class="flex items-center min-h-[10vh] justify-between px-6 md:px-16 py-4 bg-white shadow"
    >
      <div class="flex items-center gap-2">
        <img
          src="{% static 'logo.png' %}"
          class="w-[50px] h-[50px]"
          alt="Logo"
        />
        <span class="text-2xl font-bold text-blue-800"
          >Disaster Management System</span
        >
      </div>
      <div>
        <a href="/" class="text-blue-600 hover:underline"
          ><button
            id="navRegisterBtn"
            class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition"
          >
            Back
          </button></a
        >
      </div>
    </nav>
<div class="min-h-[80vh] flex items-center justify-center px-6 py-12 bg-gray-50">
    <form
      method="POST"
      class="w-2/4 bg-white p-6 rounded-lg shadow-md space-y-4"
    >
      {% csrf_token %}

      <div>
        <label
          for="id_new_password"
          class="block text-sm font-medium text-gray-700 mb-1"
          >New password</label
        >
        <input
          type="password"
          name="new_password"
          required
          id="id_new_password"
          class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        />
      </div>

      <div>
        <label
          for="id_confirm_password"
          class="block text-sm font-medium text-gray-700 mb-1"
          >Confirm password</label
        >
        <input
          type="password"
          name="confirm_password"
          required
          id="id_confirm_password"
          class="w-full px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        />
      </div>

      <button
        type="submit"
        class="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded-md transition duration-200"
      >
        Reset password
      </button>
    </form>
</div>

    <!-- Footer -->
    <footer
      class="h-min-[10vh] text-center py-6 border-t border-gray-200 bg-white text-gray-600"
    >
      &copy; 2025 Disaster Management System. All rights reserved.
    </footer>
  </body>
</html>

app/templates/common/verify_otp.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Login Page</title>
  <link href="{% static 'output.css' %}" rel="stylesheet">
</head>
<body class="bg-white min-h-[100vh] text-gray-800">

  <!-- Navbar -->
  <nav class=" flex items-center  min-h-[10vh] justify-between px-6 md:px-16 py-4 bg-white shadow">
    <div class="flex items-center gap-2">
      <img src="{% static 'logo.png' %}" class="w-[50px] h-[50px]" alt="Logo">
      <span class="text-2xl font-bold text-blue-800">Disaster Management System</span>
    </div>
    <div>
      <a href="/" class="text-blue-600 hover:underline"><button
        id="navRegisterBtn"
        class="bg-blue-600 text-white px-4 py-2 rounded-md hover:bg-blue-700 transition"
      >
        Back
      </button></a>
    </div>
  </nav>
  <div class="min-h-[80vh]">
    <form method="POST" class="max-w-md mx-auto bg-white p-6 rounded-lg shadow-md space-y-4">
        {% csrf_token %}
      
        <div>
          <label for="id_email" class="block text-sm font-medium text-gray-700 mb-1">Email:</label>
          <input type="email" name="email" value="{{email}}" readonly  id="id_email" maxlength="320" required
            class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-700 focus:border-blue-700" />
        </div>
      
        <div>
          <label for="id_otp" class="block text-sm font-medium text-gray-700 mb-1">OTP:</label>
          <input type="text" name="otp" id="id_otp" maxlength="6" required
            class="w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-700 focus:border-blue-700" />
        </div>
      
        <div>
          <button type="submit"
            class="w-full bg-blue-700 text-white font-semibold py-2 px-4 rounded-md hover:bg-blue-800 transition duration-200">
            Submit
          </button>
        </div>
      </form>
    </div>
  <!-- Footer -->
  <footer class="h-min-[10vh] text-center py-6 border-t border-gray-200 bg-white text-gray-600">
    &copy; 2025 Disaster Management System. All rights reserved.
  </footer>
</body>
</html>